export type Properties = {
  alignItems: "start" | "center" | "end";
  backgroundColor: string;
  borderBottomLeftRadius: number;
  borderBottomRightRadius: number;
  borderBottomWidth: number;
  borderColor: string;
  borderRadius: number;
  borderLeftWidth: number;
  borderRightWidth: number;
  borderTopLeftRadius: number;
  borderTopRightRadius: number;
  borderTopWidth: number;
  borderWidth: number;
  bottom: number;
  boxSizing: "border-box" | "content-box";
  boxShadow: string;
  color: string;
  display: "flex" | "hidden";
  flexDirection: "row" | "column";
  fontSize: number;
  fontWeight: number;
  gap: number;
  height: "fit" | "full" | number;
  justifyContent: "start" | "center" | "end" | "between";
  left: number;
  lineHeight: number;
  maxHeight: number;
  maxWidth: number;
  minHeight: number;
  minWidth: number;
  paddingBottom: number;
  paddingLeft: number;
  paddingRight: number;
  paddingTop: number;
  padding: number | number[];
  position: "absolute" | "relative";
  right: number;
  textAlign: "left" | "center" | "right";
  top: number;
  width: "fit" | "full" | number;
};
